# Generated by Django 6.1.1 on 2026-09-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('type_demande', models.CharField(choices=[('formation', 'Formation'), ('site_web', 'Création de site web'), ('application', 'Application / solution numérique'), ('communication', 'Communication digitale'), ('print', 'Impression'), ('media', 'Média / couverture événementielle'), ('autre', 'Autre demande')], max_length=30)),
                ('formation', models.CharField(blank=True, max_length=200)),
                ('date_souhaitee', models.DateField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, choices=[('presentiel', 'Présentiel'), ('en_ligne', 'En ligne')], max_length=20)),
                ('nombre_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
