# Generated by Django 6.1.1 on 2026-09-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='type_demande',
            field=models.CharField(choices=[('formation', 'Formation'), ('site_web', 'Création de site web'), ('application', 'Application / solution numérique'), ('communication', 'Communication digitale'), ('print', 'Impression'), ('media', 'Média / couverture événementielle'), ('partenariat', 'Collaboration / Partenariat'), ('autre', 'Autre demande')], max_length=30),
        ),
    ]
