# Generated by Django 6.1.1 on 2026-09-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_type_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='budget',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='organisation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='type_partenariat',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
