# Generated by Django 5.1.2 on 2026-09-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_budget_reservation_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duree',
            field=models.CharField(blank=True, choices=[('1_jour', '1 jour'), ('1_semaine', '1 semaine'), ('2_semaines', '2 semaines'), ('1_mois', '1 mois'), ('autre', 'Autre durée')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
