# Generated by Django 5.1.2 on 2026-09-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_duree_alter_reservation_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Demande MDT', 'verbose_name_plural': 'Demandes MDT'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_reponse',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes_internes',
            field=models.TextField(blank=True, verbose_name='Notes internes'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reponse_envoyee',
            field=models.BooleanField(default=False, verbose_name='Réponse envoyée'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type_demande',
            field=models.CharField(choices=[('formation', 'Formation'), ('site_web', 'Création de site web'), ('application', 'Application / solution numérique'), ('communication', 'Communication digitale'), ('print', 'Impression'), ('media', 'Média / couverture événementielle'), ('projet', 'Projet'), ('collaboration', 'Collaboration'), ('partenariat', 'Partenariat'), ('autre', 'Autre demande')], max_length=30),
        ),
    ]
