# Generated by Django 5.1.2 on 2026-09-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_reservation_options_reservation_date_reponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='priorite',
            field=models.CharField(choices=[('basse', '🟢 Basse'), ('normale', '🔵 Normale'), ('haute', '🟠 Haute'), ('urgente', '🔴 Urgente')], default='normale', max_length=20, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='budget',
            field=models.CharField(blank=True, max_length=100, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Demande reçue le'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_souhaitee',
            field=models.DateField(blank=True, null=True, verbose_name='Date souhaitée'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='duree',
            field=models.CharField(blank=True, choices=[('1_jour', '1 jour'), ('1_semaine', '1 semaine'), ('2_semaines', '2 semaines'), ('1_mois', '1 mois'), ('autre', 'Autre durée')], max_length=30, verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='formation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Formation / prestation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message / besoin exprimé'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='mode',
            field=models.CharField(blank=True, choices=[('presentiel', 'Présentiel'), ('en_ligne', 'En ligne')], max_length=20, verbose_name='Mode'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nom',
            field=models.CharField(max_length=150, verbose_name='Nom / entreprise'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nombre_participants',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de participants'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='organisation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Organisation / entreprise'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', '🟠 Nouvelle / En attente'), ('a_traiter', '🔵 À traiter'), ('contacte', '🟣 Contact effectué'), ('confirmee', '🟢 Confirmée'), ('en_cours', '🔷 En cours'), ('terminee', '✅ Terminée'), ('annulee', '🔴 Annulée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='telephone',
            field=models.CharField(max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type_demande',
            field=models.CharField(choices=[('formation', '🎓 Formation'), ('site_web', '🌐 Création de site web'), ('application', '💻 Application / solution numérique'), ('communication', '📣 Communication digitale'), ('print', '🖨️ Impression'), ('media', '🎥 Média / couverture événementielle'), ('projet', '💼 Projet'), ('collaboration', '🤝 Collaboration'), ('partenariat', '🤝 Partenariat'), ('autre', '📩 Autre demande')], max_length=30, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type_partenariat',
            field=models.CharField(blank=True, max_length=200, verbose_name='Type de partenariat'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
