# Generated by Django 6.1.1 on 2026-10-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_reservation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseAutomatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du modèle')),
                ('type_reponse', models.CharField(choices=[('contact', 'Contact'), ('reservation', 'Réservation')], max_length=20, verbose_name='Type')),
                ('objet', models.CharField(max_length=255, verbose_name="Objet de l'e-mail")),
                ('message', models.TextField(verbose_name='Message')),
                ('active', models.BooleanField(default=True, verbose_name='Réponse active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Réponse automatique',
                'verbose_name_plural': 'Réponses automatiques',
                'ordering': ['type_reponse', 'nom'],
            },
        ),
    ]
