# Generated by Django 6.1.1 on 2026-10-02 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_reponseautomatique'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reponse_modele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='reservations.reponseautomatique', verbose_name='Modèle de réponse'),
        ),
        migrations.AlterField(
            model_name='reponseautomatique',
            name='type_reponse',
            field=models.CharField(choices=[('contact', 'Contact'), ('reservation', 'Réservation'), ('projet', 'Projet'), ('collaboration', 'Collaboration'), ('partenariat', 'Partenariat'), ('devis', 'Demande de devis'), ('formation', 'Formation'), ('information', "Demande d'information")], max_length=20, verbose_name='Type'),
        ),
    ]
